### ISSUE TITLE
netv2 SoC dies with "ImportError: cannot import name 'LiteDRAMPort'"

### ISSUE THREAD

**Issue by mithro** [timvideos/litex-buildenv#122]
```
- make firmware check (netv2 video lm32 firmware)
---------------------------------------------
mkdir -p build/netv2_video_lm32/
time python -u ./make.py --platform=netv2 --target=video --cpu-type=lm32 --iprange=192.168.100     --no-compile-gateware \
		2>&1 | tee -a build/netv2_video_lm32//output.20190213-072531.log; (exit ${PIPESTATUS[0]})
Traceback (most recent call last):
  File "./make.py", line 164, in <module>
    main()
  File "./make.py", line 123, in main
    soc = get_soc(args, platform)
  File "./make.py", line 56, in get_soc
    exec("from targets.{}.{} import SoC".format(args.platform, args.target.lower(), args.target), globals())
  File "<string>", line 1, in <module>
  File "/home/travis/build/timvideos/HDMI2USB-litex-firmware/targets/netv2/video.py", line 2, in <module>
    from litedram.common import LiteDRAMPort
ImportError: cannot import name 'LiteDRAMPort'
real	0m0.497s
user	0m0.480s
sys	0m0.016s
make: *** [firmware-cmd] Error 1
```

**Comment by mithro** [comment]
I believe this is fixed now.
