### ISSUE TITLE
ice40_up5k_b_evn build gateway failed

### ISSUE THREAD

**Issue by fatalfeel** [timvideos/litex-buildenv#748]
export PLATFORM=ice40_up5k_b_evn
export TARGET=base
export CPU=vexriscv
export CPU_VARIANT=linux
export FIRMWARE=linux

wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
chmod +x ./litex_setup.py
./litex_setup.py init install --user

./scripts/debian-setup.sh
./scripts/download-env.sh

source ./scripts/enter-env.sh
make gateware

#error

mkdir -p build/ice40_up5k_b_evn_base_vexriscv.linux/
time python -u ./make.py --platform=ice40_up5k_b_evn --target=base --cpu-type=vexriscv --iprange=192.168.100   --cpu-variant=linux --cpu-variant=linux  \
	2>&1 | tee -a /root/icesugar/icesugar/src/advanced/litex-buildenv/build/ice40_up5k_b_evn_base_vexriscv.linux//output.20210925-052953.log; (exit ${PIPESTATUS[0]})
Compat: SoCSDRAM is deprecated since 2020-03-24 and will soon no longer work, please update. Switch to SoCCore/add_sdram/soc_core_args instead...........thanks :)

Traceback (most recent call last):
  File "./make.py", line 169, in <module>
    main()
  File "./make.py", line 123, in main
    soc = get_soc(args, platform)
  File "./make.py", line 57, in get_soc
    soc = SoC(platform, ident=SoC.__name__, **soc_sdram_argdict(args), **dict(args.target_option))
  File "/root/icesugar/icesugar/src/advanced/litex-buildenv/targets/ice40_up5k_b_evn/base.py", line 105, in __init__
    type="cached+linker")
  File "/root/icesugar/icesugar/src/advanced/litex/litex/soc/integration/soc_core.py", line 252, in add_memory_region
    linker="linker" in type))
  File "/root/icesugar/icesugar/src/advanced/litex/litex/soc/integration/soc.py", line 166, in add_region
    raise
RuntimeError: No active exception to reraise

/////////////////////
run bootstrap.sh

ompiler_rt'...
fatal: \u7248\u672c\u5eab 'https://git.llvm.org/git/compiler-rt/' \u672a\u627e\u5230
fatal: \u7121\u6cd5\u8907\u88fd 'https://git.llvm.org/git/compiler-rt' \u5230\u5b50\u6a21\u7d44\u8def\u5f91 '/root/icesugar/icesugar/src/advanced/litex-buildenv/third_party/litex/litex/soc/software/compiler_rt'
\u8907\u88fd 'litex/soc/software/compiler_rt' \u5931\u6557\u3002\u5df2\u6392\u7a0b\u91cd\u8a66\u4f5c\u696d
\u6b63\u8907\u88fd\u5230 '/root/icesugar/icesugar/src/advanced/litex-buildenv/third_party/litex/litex/soc/software/compiler_rt'...
fatal: \u7248\u672c\u5eab 'https://git.llvm.org/git/compiler-rt/' \u672a\u627e\u5230
fatal: \u7121\u6cd5\u8907\u88fd 'https://git.llvm.org/git/compiler-rt' \u5230\u5b50\u6a21\u7d44\u8def\u5f91 '/root/icesugar/icesugar/src/advanced/litex-buildenv/third_party/litex/litex/soc/software/compiler_rt'
\u7b2c\u4e8c\u6b21\u5617\u8a66\u8907\u88fd 'litex/soc/software/compiler_rt' \u5931\u6557\uff0c\u4e2d\u6b62\u4f5c\u696d
fatal: \u7121\u6cd5\u905e\u8ff4\u9032\u5b50\u6a21\u7d44\u8def\u5f91 'third_party/litex'

////////////////////
by the way way can ice40_up5k_b_evn success run simple linux or zepyhr?

**Comment by fatalfeel** [comment]
fiexd  http://fatalfeel.blogspot.com/2021/09/risc-v-on-icesugar.html
