### ISSUE TITLE
lm32-elf-objcopy: 'firmware.elf': No such file

### ISSUE THREAD

**Issue by mithro** [timvideos/litex-buildenv#76]
Issue when updating to the latest LiteX gives the following error;

```
Updating version_data.h
Updating version_data.c
# Check the version files exist
[ -e /home/tansell/github/timvideos/HDMI2USB-litex-firmware/build/opsis_video_lm32/software/include/../..//software/firmware/version_data.h ]
[ -e /home/tansell/github/timvideos/HDMI2USB-litex-firmware/build/opsis_video_lm32/software/include/../..//software/firmware/version_data.c ]
 CC       pattern.o
 CC       pll.o
 CC       processor.o
 CC       reboot.o
 CC       stdio_wrap.o
 CC       telnet.o
 CC       tofe_eeprom.o
 CC       uptime.o
 CC       version.o
 CC       /home/tansell/github/timvideos/HDMI2USB-litex-firmware/build/opsis_video_lm32/software/include/../..//software/firmware/version_data.o
 CC       /home/tansell/github/timvideos/HDMI2USB-litex-firmware/build/opsis_video_lm32/software/include/../..//software/firmware/hdmi_in1.o
cp /home/tansell/github/timvideos/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/bios/boot-helper-lm32.S boot-helper-lm32.S
 CC       boot-helper-lm32.o
 OBJCOPY  firmware.bin
lm32-elf-objcopy: 'firmware.elf': No such file
/home/tansell/github/timvideos/HDMI2USB-litex-firmware/firmware/Makefile:80: recipe for target 'firmware.bin' failed
make[1]: *** [firmware.bin] Error 1
make[1]: Leaving directory '/home/tansell/github/timvideos/HDMI2USB-litex-firmware/build/opsis_video_lm32/software/firmware'
Traceback (most recent call last):
  File "./make.py", line 164, in <module>
    main()
  File "./make.py", line 148, in main
    vns = builder.build(**dict(args.build_option))
  File "/home/tansell/github/timvideos/HDMI2USB-litex-firmware/third_party/litex/litex/soc/integration/builder.py", line 157, in build
    self._generate_software(not self.soc.integrated_rom_initialized)
  File "/home/tansell/github/timvideos/HDMI2USB-litex-firmware/third_party/litex/litex/soc/integration/builder.py", line 142, in _generate_software
    subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
  File "/home/tansell/github/timvideos/HDMI2USB-litex-firmware/build/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/home/tansell/github/timvideos/HDMI2USB-litex-firmware/build/opsis_video_lm32/software/firmware', '-f', '/home/tansell/github/timvideos/HDMI2USB-litex-firmware/firmware/Makefile']' returned non-zero exit status 2.
```

**Comment by mithro** [comment]
This seems to be caused by a change in https://github.com/enjoy-digital/litex/pull/109

**Comment by mithro** [comment]
@cr1901

**Comment by mithro** [comment]
Turns out this change is needed -> https://github.com/mithro/litex-buildenv/commit/b307f6a91d154c8514fd0eda99fbd1ea56e374dd

**Comment by mithro** [comment]
This has been fixed.
